<a href="https://colab.research.google.com/github/Bal31/FirstCode/blob/main/chapter_1_to_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## hello world program

# hello world program


1.   List item
2.   List item




In [ ]:
print("Hello World!")

Hello World!


In [ ]:
print("Baljinder\nKaur")      # new line

Baljinder
Kaur


In [ ]:
print("Baljinder\tKaur")

Baljinder	Kaur


# **variables**

In [ ]:
a=10
print(a)

10


In [ ]:
b=10.65
print(b)

10.65


In [ ]:
c="Canada"
print(c)

Canada


**Data** **Types**

In [ ]:
a=10
print(a)
print(type(a))

10
<class 'int'>


In [ ]:
b=10.65
print(b)
print(type(b))

10.65
<class 'float'>


In [ ]:
c="Canada"
print(c)
print(type(c))

Canada
<class 'str'>


In [ ]:
a=10
a=a+5
print(a)

15


In [ ]:
a=10
print(a+5)
print(a)

15
10


# Getting Values from **User**

In [ ]:
a=input()
print(a)

20
20


In [ ]:
b=input("I'm waiting please Enter a Number:")
print(b)

I'm waiting please Enter a Number:69
69


In [ ]:
x=input("Enter a Name:")
print("Hello!", x)

Enter a Name:Baljinder Kaur
Hello! Baljinder Kaur


In [ ]:
password=input("Enter your Password:")
print("Your Password is:", password)

Enter your Password:Bk$123456789
Your Password is: Bk$123456789


# Type Conversion

In [ ]:
10+"A"

TypeError: ignored

In [ ]:
a=10
b="20"

print(type(a))
print(type(b))


print(a + b)

<class 'int'>
<class 'str'>


TypeError: ignored

In [ ]:
a=10
b="20"

print(type(a))
print(type(b))

c=int(b)

print(a+c)

print(type(c))

<class 'int'>
<class 'str'>
30
<class 'int'>


In [ ]:
a=10
b="A"

print(int(b))

ValueError: ignored

In [ ]:
a=100
b=200

print(type(a))
print(type(b))

c=str(a)
d=str(b)


print(type(c))
print(type(d))

print(c + "\n \t" + d)

<class 'int'>
<class 'int'>
<class 'str'>
<class 'str'>
100
 	200


In [ ]:
a=10.65

print(a)
print(type(a))

b=int(a)

print(type(b))
print(b)

10.65
<class 'float'>
<class 'int'>
10


In [ ]:
a=input("Enter Ist Number:")
b=input("Enter IInd Number:")

c = a + "  " + b

print(c)

Enter Ist Number:6
Enter IInd Number:9
6  9


Exercise: Extract elements from numpy array a

In [ ]:
import numpy as np
a = np.array(np.arange(15).reshape(3,5))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
a[1,1:4]

array([6, 7, 8])

In [ ]:
a[:3,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a[:3,]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a[:,3]

array([ 3,  8, 13])

In [ ]:
xs = np.average(a[:3,])
xl = np.average(a[:,3])
print(xs,xl)
print("avg is:",(xs+xl)/2)

7.0 8.0
avg is: 7.5


In [ ]:
np.average(a[:2,:])

4.5

In [ ]:
a[:,1]

array([ 1,  6, 11])

In [ ]:
a[2,3:5]

array([13, 14])

In [ ]:
np.ones((2,3,4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
samplearr = np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[39,42,45,48],[51,54,57,60]])
print("Printing Input Array : \n",samplearr)

Printing Input Array : 
 [[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


In [ ]:
print("Odd Row Even column are: \n")
samplearr[1::2,0::2]

Odd Rows are: 



array([[15, 21],
       [39, 45]])

In [ ]:
#e.	Create a new NumPy array which contains the last 4 elements of the second row of “data”.  Display the new array at the end. [1 mark]

#n_array = data[1,:0:-1]
#print("New Array is:\n",n_array,"\n")

n_array = a[1,1:]
print("New Array is:\n",n_array,"\n")

#new_numpy_array = np.copy(data)
#print(new_numpy_array)
#new_a = data.copy()
#print(new_a)

New Array is:
 [6 7 8 9] 

